### ISSUE TITLE
This add-in can't be loaded due to missing dependencies

### ISSUE THREAD

**Issue by RevanthReddyT** [mrward/monodevelop-nuget-extensions#12]
The Following dependencies required by this add-in are not available: 
Required: MonoDevelop.Core v6.0, found v6.0.1
Required: MonoDevelop.Ide v6.0, found v6.0.1

Xamarin 6.0.1 (build 8) MAC

**Comment by mrward** [comment]
Yeah unfortunately there is a bug in Xamarin Studio 6.0.1 which is flagging all addins that target 6.0 as being incompatible with 6.0.1 which is incorrect. This has been fixed in Xamarin Studio but it looks like it will not be shipped until 6.0.2 of Xamarin Studio is released.

The only thing I can do is build another version of the addin that explicitly targets 6.0.1 but then that will not work with 6.0.

**Comment by mrward** [comment]
For now I have put a new 0.11.1 version of [.mpack file](https://github.com/mrward/temp-addin-upload/blob/master/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Extensions_0.11.1.mpack) on GitHub which works with Xamarin Studio 6.0.1.

**Comment by RevanthReddyT** [comment]
It worked. Thank You.
