### ISSUE TITLE
Mac: Missing MonoDevelop.PackageMangementv5.0

### ISSUE THREAD

**Issue by kswain1** [mrward/monodevelop-nuget-extensions#13]
I cannot find this add in file in this repo. I have added in theMonoDevelop.PackageManagement.Extensions_0.6.1.mpack from this repo, and ran into the error of needing an the additional add-in of MonoDevelop.PackageManagementv5.0.mpack . Can you direct me to the link for this .mpack file to resolve this issue. 

Currently using MonoDevelop 5.9.6

**Comment by mrward** [comment]
There is no 0.6.1 version of the NuGet extensions addin that I can find.

I put builds of the NuGet extensions .mpack onto a separate [repository](https://github.com/mrward/monodevelop-addins/tree/gh-pages/5.0). Unfortunately versions older than 0.6 of the NuGet extensions addin are not available since I was just publishing them on addins.monodevelop.com for a while.

The MonoDevelop.PackageManagement addin is included with MonoDevelop 5.9 itself. There is no separate .mpack to install. It has been a part of MonoDevelop since version 5.0.

**Comment by mrward** [comment]
OK I found the [0.6.1.mpack](https://github.com/mrward/temp-addin-upload). Looks like I published a temporary fix for 0.6 to allow it to work with MonoDevelop 5.9.

Version 0.7 through to 0.10 look like they should support MonoDevelop 5.9. MonoDevelop 5.10 needs version 0.11.
