### ISSUE TITLE
Support for Visual Studio for Mac 7.1

### ISSUE THREAD

**Issue by aeonblaire** [mrward/monodevelop-nuget-extensions#19]
I just updated to VSMac 7.1. The menu items are still there but nothing happens when I click them.

**Comment by mrward** [comment]
For VS Mac 7.1 you need [NuGet extensions 0.12.3](https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.1/MonoDevelop.PackageManagement.Extensions_0.12.3.mpack).

The main addin server is not picking up any changes so I am unable to publish it there.

**Comment by aeonblaire** [comment]
Nice. Thanks!

**Comment by mrward** [comment]
Re-opening this to hopefully make it more visible so it can be found instead of other issues being opened for the same problem.

**Comment by long-nguyentien** [comment]
Nice, it works

**Comment by pperera** [comment]
mrward: recommend putting some reference to this or even a Troubleshooting section in in the Readme as thats were most people end up. It was only when I considered forking and looking to resolving the issue myself that I found this. /2c

**Comment by mrward** [comment]
@pperera Ideally I would just publish it to the addin server but it does not seem to be picking up any changes. In general since I work on VS for Mac's NuGet support the NuGet extensions addin is updated shortly after any changes to VS Mac are released that break the addin. However I can only publish it to my own [addin server](https://github.com/mrward/monodevelop-addins) at the current time.

**Comment by mrward** [comment]
I have updated the readme. Instead of a Troubleshooting section I have put this information nearer the start of the readme in the Requirements section. I suspect no one will scroll down the readme very far since it is quite long and I would probably want to have the Troubleshooting section at the end.

**Comment by micdah** [comment]
Alternative to manually installing the `.mpack` file, you can also add the url `https://raw.githubusercontent.com/mrward/monodevelop-addins/gh-pages/7.2/main.mrep` as a repository in the Extension Manager, which ensures updated are picked up also, if you should choose to release a new version for 7.2.

**Comment by mrward** [comment]
@micdah A better url to use is probably http://lastexitcode.com/monodevelop-addins/7.2/main.mrep

The full set of addin urls for versions of MonoDevelop and VS Mac for the addins I maintain can be found here:

https://github.com/mrward/monodevelop-addins

**Comment by micdah** [comment]
@mrward Yes that is a good point, even better. Would probably be even better to link to, than the manual install version out on the frontpage?

**Comment by mrward** [comment]
I will add both then you can choose what you want to download the .mpack or setup another addin url
