### ISSUE TITLE
New Package (0.12.6) installs as 0.12.2

### ISSUE THREAD

**Issue by wenyonk** [mrward/monodevelop-nuget-extensions#24]
Uninstalled 0.12.5
In VS Extension Manager Gallery click on install
all prompts and version info shows as 0.12.2
![2017-12-07_09-42-06](https://user-images.githubusercontent.com/3248973/33721155-2a52b318-db34-11e7-89ce-2769a2ee14cb.png)

Works from downloading file: 
https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.3/MonoDevelop.PackageManagement.Extensions_0.12.6.mpack

Uninstall exisiting version if extension is already installed.
and installing from file via VS Extension Manager Gallery click on Install from File on lower left

**Comment by mrward** [comment]
The version available from the main extension manager is out of date and unfortunately the server seems to be not working for me so I cannot update it. So the extension is stuck at 0.12.2 on the main gallery. It is not something I can fix.

All the addins I maintain are available from a GitHub hosted addin server:

https://github.com/mrward/monodevelop-addins

You may need to use the url for the Visual Studio for Mac version you are using since some addins are not backward compatible.

**Comment by wenyonk** [comment]
Thank you for your quick response!  Please see my updated comments.

BTW 
GREAT EXTENSION!!!  HUGE TIME SAVER, SAME VS on PC EXPERIENCE, I LOVE IT!!!

THANK YOU for you contribution to the community
