### ISSUE TITLE
Update for 7.7 showed up in my 7.6.11 Visual Studio, doesn't work

### ISSUE THREAD

**Issue by gjkhw** [mrward/monodevelop-nuget-extensions#26]
https://github.com/mrward/monodevelop-addins/blob/gh-pages/7.7/MonoDevelop.PackageManagement.Extensions_0.14.mpack showed up in the Extension Manger as an update for my 7.6.11 machine. I installed it, and the UI kindly told me that it depends on 7.7 assemblies.

I uninstalled it and reinstalled the previous 0.13 version, and all is working.

I also saw that mhutch's excellent extension MSBuild Editor had its new 2.1.0 version pop up in my Visual Studio for Mac 7.6.11 install today. When installed, it will not open csproj files. Interestingly (to me) it showed up in the application update window (that is, where Visual Studio updates itself) rather than in the Extensions manager.

I uninstalled it and installed  https://addins.monodevelop.com/Stable/Mac/7.6/MonoDevelop.MSBuildEditor.MonoDevelop.MSBuildEditor-2.0.4.mpack - it is working on my machine. The download links have 7.6.11 in the path, so I had the impression that it should be working.

I wonder if the two errant updates are related to a similar root cause. Perhaps it's in Visual Studio itself, I dunno.

Issue in the other extension is here: https://github.com/mhutch/MonoDevelop.MSBuildEditor/issues/14

**Comment by mrward** [comment]
This is a problem with the addin server. I published the NuGet package management extensions only for Visual Studio for Mac 7.7. On the [addins.monodevelop.com](http://addins.monodevelop.com/Project/Index/121) page you can see only 0.14 is shown as published for 7.7.

However if you download the [root.mrep](https://addins.monodevelop.com/Beta/Mac/7.6.11/root.mrep) it includes 0.14 which is incorrect.

The problem is not specific to the NuGet Package Management Extensions. The [TFS addin](https://developercommunity.visualstudio.com/content/problem/374924/i-cant-download-team-foundation-version-control-fo.html) also has the same problem.
