### ISSUE TITLE
Stop working after VS for Mac 7.7.2 (build 21)

### ISSUE THREAD

**Issue by jzeferino** [mrward/monodevelop-nuget-extensions#28]
After the last VS for Mac update ( 7.7.2 (build 21)) the _Manage Nuget Packages_ stopped work. 

When I click on it via **solution** or **Project** it does nothing.

**Comment by mrward** [comment]
You need to update to the latest version of the NuGet extensions addin - there should be an update available on the Visual Studio Extension Repository (Beta Channel) in the Extensions manager dialog.

NuGet Extensions 0.15 works with Visual Studio for Mac 7.7.2. I updated the NuGet version in VS Mac 7.7.2 which breaks the NuGet extensions addin since they are closely coupled.
