### ISSUE TITLE
Version 0.19 is not appearing on the gallery

### ISSUE THREAD

**Issue by ravero** [mrward/monodevelop-nuget-extensions#32]
The latest version appearing on the gallery as of Visual Studio for Mac 8.2.2 is 0.18.
Version 0.19 is not appearing and I couldn't find how to download the mpack directly.

**Comment by mrward** [comment]
There is a bug in the gallery where it does not publish the new version for later minor versions. I have published 0.19 for VS Mac 8.2.2 and VS Mac 8.2.1 which should be available if you click the Refresh button in the Extensions dialog.

The addins are also available from the addin page:

http://addins.monodevelop.com/Project/Index/121

I also publish them to my own addin server, since the main monodevelop.com gallery has had problems in the past:

https://github.com/mrward/monodevelop-addins/tree/gh-pages

In VS Mac 8.3, hopefully soon, Managing NuGet packages for the solution will be available in VS Mac by default, without needing the extension to be installed. The PowerShell console will not be included 'in the box' with VS Mac.
