### ISSUE TITLE
Installation failed when installing from repository with Visual Studio for Mac 8.5

### ISSUE THREAD

**Issue by craigbrown** [mrward/monodevelop-nuget-extensions#35]
I'm using Visual Studio for Mac Professional 8.5 on High Sierra. When I try to install "Nuget Package Management Extensions" from the Extension Manager (Beta channel repository) I get an error message "The installation failed!" in red.

However, if I download the 8.5.1 file from https://addins.monodevelop.com/Project/Index/121, and use the Install From File button, it works fine. So I guess I've solved the problem for myself but thought you might want to know so it can be fixed.

When installing from repository, the messages next to the progress bar go through very quickly but I recorded them and slowed it down, and here's what they say in order:
`Requesting https://addins.monodevelop.com/Beta/Mac/8.5/MonoDe...`
`Downloading https://addins.monodevelop.com/Beta/Mac/8.5/MonoDe...`
`Requesting https://addins.monodevelop.com/Beta/Mac/8.5/MonoDe...`
`Initializing installation`
`Installing`
`Initializing installation`
`Finishing installation`
`Initializing installation`
`Installing add-ins...` <- it stays on this one with the progress bar incomplete

I checked my Ide log, but nothing gets written to it during the installation attempt.

**Comment by mrward** [comment]
No idea. The same version is published at the 8.5 url versus the 8.5.1 url on the addin server. Someone had a similar issue with a different addin and there was no error in the IDE log.

**Comment by craigbrown** [comment]
I tried installing a few other add-ins and some failed with the same message, some installed fine. So yeah, maybe this is actually a VS issue.

**Comment by mrward** [comment]
Not sure. I can repro if I use the 8.5 url but using the 8.5.2 url and it is OK. Looks to me like a server side problem since it does not seem to attempt to download the .mpack

**Comment by mrward** [comment]
Yeah it looks like the addin server does not have the .mpack available with the 8.5 url.

Does not work:

https://addins.monodevelop.com/Beta/Mac/8.5/MonoDevelop.PackageManagement.Extensions-0.21.mpack

Works:

https://addins.monodevelop.com/Beta/Mac/8.5.1/MonoDevelop.PackageManagement.Extensions-0.21.mpack

Will re-publish for 8.5 but in general there are problems with the addin server now (and have been in the past) which is why I publish all the addins over on github too - https://github.com/mrward/monodevelop-addins/tree/gh-pages

**Comment by mrward** [comment]
Re-publishing for 8.5 individually seems to have fixed the problem (at least with the NuGet extensions addin).
