### ISSUE TITLE
All comboboxes are read only

### ISSUE THREAD

**Issue by ninjaboy** [mrward/monodevelop-nuget-extensions#6]
In Xamarin 5.9.7 when I open package manager console extension it has all comboboxes readonly with no data populated. So basically nothing can be done at all.
Please let me know where to enable logs and where to get them to provide to you for more information.

**Comment by mrward** [comment]
The combo boxes in the Package Manager Console extension normally get shown as read-only if there is a mismatch between the NuGet version used by the addin and the version used by Xamarin Studio. You normally see a type load exception on the Mac in the IDE log (Help - Open Log Directory), but it works fine on Windows

Xamarin Studio 5.9.7 uses NuGet 2.8.5 so you should be using NuGet extension addin version 0.10 which is available from the beta channel.

Xamarin Studio 5.10 uses NuGet 2.8.7 so that needs NuGet extension addin version 0.10.1 which is available on the alpha channel.

You can also download the .mpacks directly from [my addins github repository](https://github.com/mrward/monodevelop-addins/tree/gh-pages/5.0).
